### ISSUE TITLE
Publish to Maven

### ISSUE THREAD

**Issue by vectro** [IndabaConsultores/LightCouch#14]
Is there any chance that the 0.2.2 release could be pushed to jitpack or apache repositories?

**Comment by jjrodrig** [comment]
@vectro  Thanks for your interest

 The releases of this fork are pusblished via jitpack. You can use it including this dependency in your pom.

```
<dependency>
	<groupId>com.github.IndabaConsultores</groupId>
	<artifactId>lightCouch</artifactId>
	<version>0.2.2</version>
</dependency>
```
