### ISSUE TITLE
CouchDbInfo: disk_size is deprecated

### ISSUE THREAD

**Issue by DeanDSA** [IndabaConsultores/LightCouch#28]
The model for database info uses **sizes** object, resulting in **disk_size** in CouchDbInfo always being zero.

The model from couchdb:
{
  "db_name": "database name",
  "purge_seq": "ps",
  "update_seq": "us",
  **"sizes"**: {
    "file": 3383724,
    "external": 5643290,
    "active": 3287056
  },
  "props": {},
  "doc_del_count": 0,
  "doc_count": 3574,
  "disk_format_version": 8,
  "compact_running": false,
  "cluster": {
    "q": 2,
    "n": 1,
    "w": 1,
    "r": 1
  },
  "instance_start_time": "0"
}

**Comment by jjrodrig** [comment]
Hi @DeanDSA 

This library tries to keep the compatibility with previous CouchDB versions. 
**disk_size** is used by 1.x versions and has been replaced by **sizes** in 2.x and 3.x versions. 

Are you proposing adding support for the **sizes** attribute in CouchDBInfo when using CouchDB 2.x/3.x?

Thanks
