### ISSUE TITLE
Add support for ETAG management for recurrent requests optimization

### ISSUE THREAD

**Issue by jjrodrig** [IndabaConsultores/LightCouch#6]
CouchDB provides a ETAG based mechanism that allow to the client to cache some of the results and to optimize the processing in the server side as the full response is not required if nothing has changed. 

> You can send an If-None-Match header along with your GET request. If there is a new version, the server will send it. Otherwise, it sends back a 300 Not Modified header

Currently the API does not support the ETAG management. It could be interesting to expose this mechanism

**Comment by yzhan94** [comment]
ETAG management API was defined in PR #23, with the new method *findIfNotModified*.
